default_language_version:
    python: python3

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
    -   id: pyupgrade
        language_version: python3
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        language_version: python3
        exclude: .rvc|.rvh|.rvi|.rvp|.rvt|.tpl|.txt
    -   id: end-of-file-fixer
        language_version: python3
        exclude: .ipynb|.rvc|.rvh|.rvi|.rvp|.rvt|.tpl|.txt
    -   id: check-yaml
        language_version: python3
    -   id: debug-statements
        language_version: python3
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3
        args: ['--config=setup.cfg']
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        language_version: python3
        args: ['--profile', 'black', '--filter-files']
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
    -   id: pydocstyle
        language_version: python3
        args: ['--convention=numpy', '--match="(?!test_).*\.py"']
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes

ci:
  autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks
        for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
