name: ravenpy-env
channels:
- zeitsperre
- conda-forge
- defaults
dependencies:
  - raven ==3.0.4.318
  - ostrich ==21.03.16
  - python>=3.7
  - affine
  - click
  - climpred>=2.1
  - clisops>=0.5.1
  - dask<=2021.02.0
  - fiona
  - gdal>=3.0.0
  - geopandas>=0.9.0
  - lxml
  - matplotlib
  - numpy
  - owslib
  - pandas
  - pip
  - proj
  - pydantic
  - pyparsing
  - pyproj>=3.0.0
  - rasterio
  - requests
  - rioxarray
  - scipy
  - scikit-learn=0.24.1
  - shapely
  - statsmodels
  - xarray==0.17
  - xclim>=0.23
  - xskillscore
  - pre-commit
  - setuptools>50.0
  - wheel
  - holoviews
  - hvplot
