name: ravenpy-env
channels:
- conda-forge
- defaults
dependencies:
  - raven-hydro ==3.0.4.322
  - ostrich ==21.03.16
  - python >=3.7
  - affine
  - cf_xarray
  - click
  - climpred >=2.1
#  - clisops ==0.5.0
  - dask
  - fiona
  - gdal >=3.0.0
  - geopandas >=0.9
  - lxml
  - matplotlib
  - numpy
#  - owslib
  - pandas<1.3
  - pip
  - pydantic
  - pyproj>=3
  - rasterio
  - requests
  - rioxarray
  - scipy
  - scikit-learn ==0.24.2
  - shapely
  - statsmodels
  - xarray >=0.18
  - xclim >=0.26.1
  - xskillscore
  - pre-commit
  - setuptools >50.0
  - wheel
  - holoviews
  - hvplot
  - pip:
    - owslib @ git+https://github.com/geopython/OWSLib.git@master
