name: ravenpy-env
channels:
- conda-forge
- defaults
dependencies:
  - raven-hydro ==3.0.4.322
  - ostrich ==21.03.16
  - python >=3.7
  - affine
  - cf-xarray
  - click
  - climpred >=2.1
  - clisops >=0.6.4
  - dask <=2021.02.0
  - fiona
  - gdal >=3.0.0
  - geopandas >=0.9
  - lxml
  - matplotlib
  - numpy
  - owslib
  - pandas
  - pip
  - pydantic
  - pyproj>=3
  - rasterio
  - requests
  - rioxarray
  - scipy
  - scikit-learn ==0.24.1
  - shapely
  - statsmodels
  - xarray >=0.18
  - xclim >=0.26.1
  - xskillscore
  - pre-commit
  - setuptools >50.0
  - wheel
  - holoviews
  - hvplot
